#!/usr/bin/env python
"""
Controller Constants - Konstanten für Controller-Eingaben
"""

# Achsen
AXIS_LEFTX = 0
AXIS_LEFTY = 1
AXIS_RIGHTX = 2
AXIS_RIGHTY = 3
AXIS_TRIGGERLEFT = 4
AXIS_TRIGGERRIGHT = 5

# Buttons
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_BACK = 6
BUTTON_START = 7
BUTTON_LEFTSTICK = 8
BUTTON_RIGHTSTICK = 9
BUTTON_LEFTSHOULDER = 4
BUTTON_RIGHTSHOULDER = 5
BUTTON_DPAD_UP = 10
BUTTON_DPAD_DOWN = 11
BUTTON_DPAD_LEFT = 12
BUTTON_DPAD_RIGHT = 13
BUTTON_GUIDE = 14  # Xbox Button / PS Button

# Schwellenwerte für Achsen
AXIS_DEADZONE = 0.2
